services:
  nginx:
    image: nginx:latest
    container_name: mclogs-nginx
    ports:
      - "9300:9300"
    volumes:
      - ../:/web/mclogs
      - ./mclogs.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - mclogs-network

  php-fpm:
    container_name: mclogs-php
    build:
      dockerfile_inline: |
        FROM php:8.1-fpm
        COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
        RUN install-php-extensions mongodb redis
        COPY mclogs.ini /usr/local/etc/php/conf.d/mclogs.ini
    volumes:
      - ../:/web/mclogs
    depends_on:
      - mongo
      - redis
    networks:
      - mclogs-network

  mongo:
    image: mongo:latest
    container_name: mclogs-mongo
    volumes:
      - mongo:/data/db
    networks:
      - mclogs-network

  redis:
    image: redis:7-alpine
    container_name: mclogs-redis
    volumes:
      - redis:/data
    networks:
      - mclogs-network

volumes:
  mongo:
  redis:

networks:
  mclogs-network:
    name: mclogs-network
